# program settings
rngSeed: 1234
# simulation box
simBoxLow: [0, 0, 0]
simBoxHigh: [25, 25, 25]
simBoxPBC: [true, true, false]
monolayer: false
# initialization box
initBoxLow: [0, 0, 0]
initBoxHigh: [25, 25, 25]
initCircularX: false
# components outside [-1,1] will be randomly set
initOrient: [2, 2, 0]
# physical settings
viscosity: 0.01 #pN/(um^2.s)
KBT: 0.00411 #pN.um, 300K
linkKappa: 1000.0 # pN/um spring constant for sylinder links.
# Sylinder
sylinderFixed: false
sylinderNumber: 400
sylinderLength: 3.0
sylinderLengthColRatio: 1.0
sylinderLengthSigma: -1.0 # <0 means no randomness
sylinderDiameter: 1.0
sylinderDiameterColRatio: 1.0
sylinderColBuf: 1.0
# time-stepping
dt: 0.001 # s
timeTotal: 1.0 # s
timeSnap: 0.01 # s
# ConstraintSolver
conResTol: 1e-5 # residual
conMaxIte: 100000 # max iteration
conSolverChoice: 0 # 0 for BBPGD, 1 for APGD, etc
# Boundaries
boundaries:
  - type: "wall"
    center: [5, 5, 5]
    norm: [1, 1, 0]
  - type: "wall"
    center: [0, 0, 20]
    norm: [0, 0, -1]
  - type: "tube"
    center: [12, 12, 12]
    radius: 8
    axis: [1, 1, 1]
    inside: true
  - type: "sphere"
    center: [12, 12, 12]
    radius: 10
    inside: true
